name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          
          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          # (Optional) Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure Password
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper   = [char[]](65..90)      # A-Z
              Lower   = [char[]](97..122)     # a-z
              Number  = [char[]](48..57)      # 0-9
              Special = ([char[]](33..47) + [char[]](58..64) +
                         [char[]](91..96) + [char[]](123..126)) # Special characters
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          
          echo "RDP_CREDS=User: RDP | Password: $password" >> $env:GITHUB_ENV
          
          if (-not (Get-LocalUser -Name "RDP")) {
              Write-Error "User creation failed"
              exit 1
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Install Emulator
        run: |
          $mumuUrl = "https://a11.gdl.netease.com/MuMu_5.0.4_gw-overseas12_all_1756398237.exe?n=MuMu_5.0.4_rasQQMC.exe"
          $mumuInstaller = "$env:TEMP\MuMu_5.0.4_rasQQMC.exe"
          
          # Install
          Invoke-WebRequest -Uri $mumuUrl -OutFile $mumuInstaller
          
          # Install
          Start-Process -FilePath $mumuInstaller -ArgumentList "/S" -Wait
          
          # Verify installation (check if the executable exists in the default install path)
          $mumuPath = "$env:ProgramFiles\MuMu\MuMu.exe"
          if (-not (Test-Path $mumuPath)) {
              Write-Error "MuMu Emulator installation failed"
              exit 1
          }
          
          # Run ground
          Start-Process -FilePath $mumuPath -NoNewWindow
          
          # Clean up installer
          Remove-Item $mumuInstaller -Force

      - name: install Files to Folder
        run: |
          $downloadsFolder = [Environment]::GetFolderPath("MyDocuments") + "\..\Downloads"
          
          # Ensure folder exists
          if (-not (Test-Path $downloadsFolder)) {
              New-Item -Path $downloadsFolder -ItemType Directory -Force
          }
          
          # install
          $deltaUrl = "https://delta.filenetwork.vip/file/Delta-2.693.960.apk"
          $deltaPath = "$downloadsFolder\Delta-2.693.960.apk"
          Invoke-WebRequest -Uri $deltaUrl -OutFile $deltaPath
          
          # Verify Delta APK download
          if (-not (Test-Path $deltaPath)) {
              Write-Error "Failed to download Delta APK"
              exit 1
          }
          
          # install
          $clickerUrl = "https://dw.uptodown.net/dwn/IUeT51YJps5NIJYvHXwsWvRZmlVzOjMqpjdgO_JCVjdD8cRntWgz3nEiAaqR7j5W-Wa2YLzIJEJBedwD_4KEBNmFv5Se1kGk67Ol0en1hP1e8suoK_XHLUP_hGbj5PS_/AHUbggwlDeGTc0W_Yr-MToxQMoZ2mBuPpd3gDwMBodnD4N81HhrqrAoJH65bz2Id_vkhL3vJVZF5k7H27lpyhJaGbFnSnOjUxMwibd7slveCF8lcsr2uholZwnCTPz-Q/QZ_xt13TLiMq6eRpP3Bvi8OdVkuDerT2KXgS82OeoVcFEr8Zm9LMki9JBP7Fo4mqVQaSqewcONN64wx0vw3GA3RzfZ_PJdGrDu014Z__B9A=/auto-clicker-automatic-tap-2-3-0.apk"
          $clickerPath = "$downloadsFolder\auto-clicker-automatic-tap-2-3-0.apk"
          Invoke-WebRequest -Uri $clickerUrl -OutFile $clickerPath
          
          # verify
          if (-not (Test-Path $clickerPath)) {
              Write-Error "Failed to download Auto Clicker APK"
              exit 1
          }

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and set a unique hostname
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
      
      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          
          # Test connectivity using Test-NetConnection against the Tailscale IP on port 3389
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Maintain Connection
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: RDP"
          Write-Host "Password: $(echo $env:RDP_CREDS)"
          Write-Host "==================`n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
